<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Email.Tes</AssemblyName>
        <RootNamespace>Emai.Tes</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Core.csproj" />
    </ItemGroup>

</Project>
